### ISSUE TITLE
No longer fetching results

### ISSUE THREAD

**Issue by megaroeny** [kevinwuhoo/vector-logos-figma-plugin#1]
When I search for something, it just keeps loading and no results are ever returned. I tried both on desktop and web apps. ☹️ 

![image](https://user-images.githubusercontent.com/1559447/93931887-6169e500-fced-11ea-8c8b-918f15b3f475.png)

**Comment by kevinwuhoo** [comment]
Thanks for reporting this! I can't seem to reproduce this, maybe one of the intermediate services that it queries was down or buggy earlier today? Can you give it another try?

I do think that if the request errored it could end up in that infinitely loading state. Will take a look at that code path more closely and add that fix.

This is what I see right now when I search for bevy:

<img width="501" alt="Screen Shot 2020-09-22 at 20 36 27" src="https://user-images.githubusercontent.com/531488/93964034-748fab80-fd13-11ea-87fe-304c20c797ca.png">

Here's a gif of me searching for Github:

![Sep-22-2020 20-41-15](https://user-images.githubusercontent.com/531488/93964235-013a6980-fd14-11ea-962c-0f11088bde89.gif)

**Comment by megaroeny** [comment]
Okay, I had to wait a while but it eventually showed results! Thanks!
